version: '3.9'

services:
  # MongoDb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    
  # API service
  api:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      HTTP_HOST: 0.0.0.0
      PORT: 8080
      LOG_LEVEL: debug
      DATABASE_URL: mongodb://mongo_db:27017/tasty  
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
